# Generated by Django 4.2.2 on 2023-06-11 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('passw', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
